### ISSUE TITLE
新账号登陆以后闪退

### ISSUE THREAD

**Issue by areslan1122** [dragonflyoss/console#24]
### Bug report:

注册账号，登陆以后闪退. 使用 main/main-rc branch都一样。
### Environment:
- Dragonfly console version:
- OS: mac/ubuntu16.04 
- Kernel (e.g. `uname -a`): 
- Others:

**Comment by jim3ma** [comment]
是 manager 进程退出了么？

**Comment by jim3ma** [comment]
是 manager 进程退出了么？

**Comment by gaius-qi** [comment]
启动方式是怎样的，`helm charts` 还是镜像直接部署的。

**Comment by areslan1122** [comment]
@gaius-qi 谢谢回复。

是拉下来代码直接 yarn start 的。 如果是你们这边没有办法复现的话，我可以补充运行环境和相关的日志信息（如果有错误日志的话）

**Comment by gaius-qi** [comment]
> @gaius-qi 谢谢回复。
> 
> 是拉下来代码直接 yarn start 的。 如果是你们这边没有办法复现的话，我可以补充运行环境和相关的日志信息（如果有错误日志的话）

给我贴发下错误日志吧，manager server 的日志和前端的(包括浏览器 console 的)

**Comment by areslan1122** [comment]
重新启动看了一下，后段没有打出来相关日志。阅览器 console 也没有错误日志，都是200或304的正常请求

**Comment by yxxhero** [comment]
@areslan1122 闪退指的是退出到登录页么 非常感谢
