### ISSUE TITLE
When adding preheat, the incoming scheduler-cluster of the request and the scheduler-cluster of the response data are different

### ISSUE THREAD

**Issue by Liam-Zhao** [dragonflyoss/console#337]
### Bug report:

API:
![image](https://github.com/dragonflyoss/console/assets/107842350/e2ed463c-7960-418a-8f0f-95e35e2fc23f)

requset:
![image](https://github.com/dragonflyoss/console/assets/107842350/98851b5b-1bc6-4e96-b70b-dd05480fc49e)

response:

![image](https://github.com/dragonflyoss/console/assets/107842350/58e10ed9-f7b1-4db3-b819-eee84cac17cf)

API:
![image](https://github.com/dragonflyoss/console/assets/107842350/0b4566b6-bbe7-47a3-8c90-dc7ecb185983)

response:
![image](https://github.com/dragonflyoss/console/assets/107842350/2f0c25e3-98bf-41d5-a31a-337153d7ab79)

API:
![image](https://github.com/dragonflyoss/console/assets/107842350/50f31dda-fea4-413b-8ebd-75ff3ff20967)

response:
![image](https://github.com/dragonflyoss/console/assets/107842350/a246cff0-4241-4589-971c-67cb7ec0fa6d)

**Comment by gaius-qi** [comment]
@Liam-Zhao Your cluster has no active scheduler.
